### PR TITLE
Add release job to CI

### LINKED ISSUE #3: Make a ZIP release
Instead of describing what to do with GitHub and Composer we could have a CI job that creates an installation ZIP and uploads it to GitHub releases every time the repo is tagged.

What do you think?

### PR DESCRIPTION
**Pull request by szepeviktor**
Needs an English speaking person who edits README.

Closes #3

### CODE REVIEW

**Comment by szepeviktor** [comment]
https://github.com/szepeviktor/wp-rest-api-auth0/releases 👀

**Comment by joshcanhelp** [comment]
@szepeviktor - Thank you for this! Just so I'm clear, this creates a release ZIP with the dependencies installed to make the manual process a bit easier? Does this (or is there any way to) make a ZIP that you can just upload into the admin? Maybe by adding plugin headers to the main file?

**Comment by szepeviktor** [comment]
> a ZIP that you can just upload into the admin

Is there a way to install an MU plugin from WordPress admin??

**Comment by joshcanhelp** [comment]
You can have the same file in MU plugins as you can in regular plugins and it will work, as long as you have a plugin header on the file (IIRC).

**Comment by szepeviktor** [comment]
I leave this plugin up to you. I am sorry for the noise.
I manufacture plugins for agency use done by my playbook.

If one manufactures plugins for the masses without expertise it'll be slower, less secure, basically you have to put in safeguards because the lack of expertise of the user.
I'm an old-style guy: hosting is only for scientists.

**Comment by joshcanhelp** [comment]
@szepeviktor - This is not noise at all and no apology needed! I really appreciate your contributions.

I'd like to get this working for as many different use cases as possible, if possible. I just don't see how including the main file, which calls `add_action` could even happen with this as a Composer package unless you're manually requiring the main file at some point on your own, which will break if the file structure in the package breaks.

**Comment by szepeviktor** [comment]
I see 2 ways.

1. Average user downloads a prepared ZIP file from GitHub release and unpacks it to `wp-content/mu-plugins/`
2. Agencies do `composer require ...` and copy the bundled loader to `wp-content/mu-plugins/`

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
Please modify README accordingly.

**Pull request merged**
